module.exports = {
  defaultSeverity: 'warning',
  customSyntax: 'postcss-scss',
  extends: ['stylelint-config-standard-scss'],
  plugins: ['stylelint-declaration-strict-value'],
  ignoreFiles: ['dist/**', 'coverage/**', '.angular/**', 'node_modules/**'],
  rules: {
    'scale-unlimited/declaration-strict-value': [
      [
        'color',
        'background',
        'background-color',
        'border',
        'border-color',
        'border-top',
        'border-right',
        'border-bottom',
        'border-left',
        'outline',
        'outline-color',
        'box-shadow',
        'text-shadow',
        'fill',
        'stroke',
        'font-size',
        'font-weight',
        'line-height',
        'letter-spacing',
        'margin',
        'margin-top',
        'margin-right',
        'margin-bottom',
        'margin-left',
        'padding',
        'padding-top',
        'padding-right',
        'padding-bottom',
        'padding-left',
        'gap',
        'row-gap',
        'column-gap',
        'border-radius',
        'border-width',
        'width',
        'height',
        'max-width',
        'max-height',
        'min-width',
        'min-height',
        'top',
        'right',
        'bottom',
        'left',
      ],
      {
        ignoreValues: [
          '0',
          'none',
          'auto',
          'inherit',
          'initial',
          'unset',
          'transparent',
          'currentColor',
          'bold',
          'normal',
        ],
        ignoreFunctions: true,
      },
    ],
    'alpha-value-notation': null,
    'comment-empty-line-before': null,
    'declaration-empty-line-before': null,
    'font-family-name-quotes': null,
    'hue-degree-notation': null,
    'no-empty-source': null,
    'selector-class-pattern': null,
  },
};
